In [3]:
import numpy as np

print(np.__version__)

1.24.2


In [4]:
arr = np.arange(0,10,1)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr = np.full((3,3), True, dtype=bool)
arr

#np.ones((3,3), dtype=bool) #metodo alternativo

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

impares = arr[arr % 2 != 0]

impares


array([1, 3, 5, 7, 9])

In [13]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0] = -1

arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [15]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

out = arr.copy()

out[out % 2 != 0] = -1
print(f'Out\n{out}')
out
print('Arr\n')
arr

Out
[ 0 -1  2 -1  4 -1  6 -1  8 -1]
Arr



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr = np.arange(10)
arr

a = arr.reshape(2,5)
#a = arr.reshape(2-1) # con -1 automaticamente decide el numero de columnas
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

c = np.concatenate((a,b))
             

c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

c = np.concatenate((a,b),axis=1)
             
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [26]:
a = np.array([1,2,3])

b = np.r_[np.repeat(a, 3), np.tile(a, 3)]

b

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])