# Práctica Clase 3

## Numpy

In [2]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* Se pueden hacer varios tipos de operaciones en ambos elementos por ejemplo agregar o quitar elementos, ordenar o hacer operaciones matematicas.

In [2]:
#agregar en lista
lista = [1,2,3]
lista.append(4)
lista


[1, 2, 3, 4]

In [11]:
#agrega en un arreglo Numpy
arreglo = np.array([1,2,3])
arreglo2 = np.array([4])
arreglo3 = np.concatenate((arreglo, arreglo2))
arreglo3

array([1, 2, 3, 4])

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* Algunas cosas que se pueden hacer en Numpy y no en una lista son por ejemplo multiplicar matrices, funciones matematicas como sin(), cos(), exp()

In [18]:
arreglo = np.arange(start=2, stop=12,  step = 2)
print(arreglo)
potencia = np.power(2, arreglo)
print(potencia)


[ 2  4  6  8 10]
[   4   16   64  256 1024]


**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

In [23]:
#(n,) arreglo unidimencional
a =  np.array([1,2,3])
print(f'a: {a.shape}')
print(a)

#(n,1) arreglo bidimencional con 1 columna y n filas

b = np.array([[1], [2], [3]])
print(f'b: {b.shape}')
print(b)

#(1,n) contrario al ejemplo anterio este tendra 1 fila y n columnas

c = np.array([[1,2,3]])
print(f'c: {c.shape}')
print(c)


a: (3,)
[1 2 3]
b: (3, 1)
[[1]
 [2]
 [3]]
c: (1, 3)
[[1 2 3]]


A partir de una lista podemos crear un arreglo de numpy

In [30]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [3]:
arreglo = np.arange(8)
print(arreglo)

[0 1 2 3 4 5 6 7]


Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento

In [25]:
lista + 1

TypeError: can only concatenate list (not "int") to list

In [26]:
arreglo = arreglo + 1

In [27]:
arreglo

array([1, 2, 3, 4, 5, 6])

2. Elevar al cuadrado todos los elementos

In [8]:
lista**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [28]:
arreglo**2

array([ 1,  4,  9, 16, 25, 36])

3. Sumar todos los elementos

In [33]:
print(arreglo.sum())
print(lista.sum())

15


AttributeError: 'list' object has no attribute 'sum'

In [34]:
n = 0
for e in lista:
    n = n + e
print(n)

15


In [35]:
arreglo.shape

(6,)

In [36]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (3, 6) 



In [37]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]] . Shape = (1, 6) 



In [38]:
arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [25]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto


Arreglo de (n,)
[1 2 3 4 5 6] . Shape = (6,) 

Arreglo de (2,n)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (2, 6) 

Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1)


In [3]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1)


In [5]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1.shape

(2, 4)

In [6]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2.shape

(2, 4)

In [7]:
a3 = a1 * a2
a3.shape

(2, 4)

In [43]:
a3

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange

In [8]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Ejercicio 2**:
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [9]:
arr2 = np.linspace(0,9,100)
arr2

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        , 1.09090909, 1.18181818, 1.27272727,
       1.36363636, 1.45454545, 1.54545455, 1.63636364, 1.72727273,
       1.81818182, 1.90909091, 2.        , 2.09090909, 2.18181818,
       2.27272727, 2.36363636, 2.45454545, 2.54545455, 2.63636364,
       2.72727273, 2.81818182, 2.90909091, 3.        , 3.09090909,
       3.18181818, 3.27272727, 3.36363636, 3.45454545, 3.54545455,
       3.63636364, 3.72727273, 3.81818182, 3.90909091, 4.        ,
       4.09090909, 4.18181818, 4.27272727, 4.36363636, 4.45454545,
       4.54545455, 4.63636364, 4.72727273, 4.81818182, 4.90909091,
       5.        , 5.09090909, 5.18181818, 5.27272727, 5.36363636,
       5.45454545, 5.54545455, 5.63636364, 5.72727273, 5.81818182,
       5.90909091, 6.        , 6.09090909, 6.18181818, 6.27272727,
       6.36363636, 6.45454545, 6.54545455, 6.63636364, 6.72727

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [11]:
arr3 = np.arange(10, 100)
mask = arr3 % 3 == 0
filtrado = arr3[mask]


array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [39]:
arr4 = np.zeros((5,10))
print(arr4.shape)
print(arr4)
arr4[1,:]=1
print('\n')
print(arr4)
arr4[3,:]=1
print('\n')
print(arr4)
arr4[:,2]=2
print('\n')
print(arr4)
arr4[:,7]=2
print('\n')
print(arr4)

(5, 10)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


[[0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]]


[[0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]]


**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html

In [41]:
a = np.random.random((4,2,3)) * 100 + 100
a

array([[[183.13774953, 124.03500903, 138.70592793],
        [194.43754743, 113.27466364, 189.652081  ]],

       [[124.54022598, 130.19319533, 162.62440499],
        [132.63786299, 184.08198064, 168.65083604]],

       [[173.61421666, 149.21524811, 174.50485887],
        [167.02850625, 189.07346312, 160.14037557]],

       [[140.12670536, 172.10452184, 159.85660607],
        [125.22949489, 182.5860948 , 193.51920349]]])

In [47]:
a = np.random.random((4,4))

In [48]:
a

array([[0.47464564, 0.70212237, 0.61362814, 0.78509216],
       [0.4199223 , 0.59472579, 0.85248849, 0.39702101],
       [0.15092158, 0.09222533, 0.34362887, 0.67759838],
       [0.24653493, 0.93926889, 0.40555495, 0.23467814]])

In [49]:
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int8)

/tmp/ipykernel_7113/3651563978.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 200 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int8)


In [50]:
a

array([[ 10, -56,  30,  45,   5,  50],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]], dtype=int8)

In [51]:
a.sum()

519

In [52]:
a.std()

23.924904214367643

In [53]:
a.sort(axis=1)

In [54]:
a

array([[-56,   5,  10,  30,  45,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50]], dtype=int8)

In [55]:
a.sort(axis=0)
a

array([[-56,   5,  10,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  45,  50]], dtype=int8)

In [56]:
a[1:3,0:3]

array([[ 0,  5, 20],
       [ 0,  5, 20]], dtype=int8)

In [67]:
l =   [[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]]

In [68]:
a = np.array([l])

In [69]:
a.shape

(1, 4, 6)

In [60]:
a.reshape(24)

array([ 10, 200,  30,  45,   5, 100,   5,  20,  30,  40,  50,   0,   5,
        20,  30,  40,  50,   0,   5,  20,  30,  40,  50,   0])

In [33]:
a = np.matrix([[1,2,3,4,5,6]]) 
print(a) 

[[1 2 3 4 5 6]]


In [62]:
b = np.matrix([[1],[2],[3],[4],[5],[6]]) 
print(b) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [65]:
c = a * b 
print(c) 

[[1305  545  545  545]]


In [66]:
d = b * a 
print(d)

ValueError: shapes (6,1) and (4,6) not aligned: 1 (dim 1) != 4 (dim 0)